[build]
  publish = "."

[[redirects]]
  from = "/privacy"
  to = "https://github.com/ProdigyV21/ARVIO/blob/main/PRIVACY.md"
  status = 302
  force = true

[[redirects]]
  from = "/app"
  to = "https://web.arvio.tv"
  status = 302
  force = true

[[redirects]]
  from = "/app/*"
  to = "https://web.arvio.tv/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/go/premium"
  to = "https://web.arvio.tv/?utm_source=arvio.tv&utm_medium=website&utm_campaign=premium&intent=trial"
  status = 302
  force = true
