[build]
  publish = "."

[[redirects]]
  from = "/app"
  to = "https://streamnet-sync.netlify.app/login"
  status = 302
  force = true

[[redirects]]
  from = "/app/*"
  to = "https://streamnet-sync.netlify.app/:splat"
  status = 302
  force = true
